### PR TITLE
Considers looking for a stdlib address injected with deploy-all

### LINKED ISSUE #50: Using deploy-all injects a stdlib but sync can't find it's address
When using deploy-all, a stdlib's contracts are deployed in a directory and this directory's address is written into the package.zos.network.json file.

However, if he sync command is ran afterwards, the stdlib's deployed address is sought for within the node_modules package, ignoring the injected version.

As a result, using deploy-all is not really usable as is.

### PR DESCRIPTION
**Pull request by ajsantander**
Fixes #50

### CODE REVIEW

**Comment by facuspagnuolo** [comment]
I think we should prioritize local-deployed stdlibs instead, do you agree?
I'm saying just based on how `sync` works right now (see [here](https://github.com/zeppelinos/zos-cli/blob/b1d82a1803e61e4975adef6eb9a746dc39a4b6b9/src/scripts/sync.js#L39-L41))

**Comment by frangio** [comment]
Instead of using `try ... catch` blocks, I think this could be implemented by checking if the files exist first.

**Comment by spalladino** [comment]
See #58

**Comment by spalladino** [comment]
Implemented as #58

**Pull request closed without merging**
