### PR TITLE
Make travis tests faster

### PR DESCRIPTION
**Pull request by itstehkman**
Potential fix to #148

First attempt (commit 866972a) is by vm parallelization
https://docs.travis-ci.com/user/speeding-up-the-build/#Parallelizing-your-builds-across-virtual-machines
Results were terrible, too much overhead on setup: https://travis-ci.org/zeppelinos/zos-cli/builds/388603593

Second attempt (commit dd1cf91) is process parallelization by running npm test on each file in parallel with 4 processes running at a time. Again, terribly slow, but not sure why.

### CODE REVIEW

**Comment by itstehkman** [comment]
@maraoz would you be willing to consider any test parallelization framework such as https://github.com/yandex/mocha-parallel-tests or 
https://github.com/hillstreetlabs/espresso?

Mocha parallel tests looks enticing, but I'm not sure how compatible it is with truffle's testing framework, which is built ontop of Mocha.

**Comment by facuspagnuolo** [comment]
Hi @itstehkman, espresso could be a good idea!

**Comment by facuspagnuolo** [comment]
@itstehkman any update on this? I think it was looking good, but it is a bit outdated with master now, would you mind reviving this PR?

**Comment by itstehkman** [comment]
@facuspagnuolo sorry for the delay, been busy. I talked with the espresso folks a bit to merge a PR in their repo that would make testing in this repo easier. I'll take a look again tomorrow night.

**Comment by spalladino** [comment]
Hey @itstehkman, wanted to let you know we're closing this repo in favour of a monorepo at zeppelinos/zos. If you are still working on this, let us know and please migrate your work there! Thanks!

**Pull request closed without merging**
